server:
  port: 0
spring:
  application:
    name: user-application
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password:
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    status-page-url-path: ${management.endpoints.web.exposure.}/health
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health

