spring:
  profiles:
    active: local
    include: datasource
    group:
      local: local-db
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      globally_quoted_identifiers: true
      jdbc:
        time_zone: UTC
      org:
        hibernate:
          envers:
            store_data_at_delete: true
  flyway:
    locations:
      - classpath:db/migration, db/{vendor}
