spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: h2-db
  datasource:
    url: jdbc:h2:mem:commerce;
    username: sa
    password:

---

spring:
  config:
    activate:
      on-profile: mysql-db
  datasource:
    url: jdbc:mysql://localhost:3306/commerce
    username: root
    password: password

---

