POST http://localhost:8000/order-service/orders
Content-Type: application/json

{
  "productId": "CATALOG-001",
  "quantity": 10,
  "unitPrice": 1500,
  "userId": "{{$random.uuid}}"
}

> {%
    client.global.set("userId", response.body.userId);
%}

###


GET http://localhost:8000/order-service/orders?userId={{userId}}
Content-Type: application/json