services:
  yongpang-product-db:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: product
    ports:
      - "3306:3306"
    volumes:
      - ./ini
      - ./mysql/logs:/logs
